### ISSUE TITLE
Could it support redmine 3.2.X?

### ISSUE THREAD

**Issue by archonwang** [phoebusnetto/redmine_tracker_status_trigger#1]
Could it support redmine 3.2.X?

Thanks

**Comment by phoebusnetto** [comment]
Hi, @archonwang, did you tried this version on redmine 3.2.x? Found some error? If you did, please report to me, it will help! :)

We will upgrade our Redmine to Version 3.2.x asap, so i'll include support to this version, but if you found something and could share i would appreciate.

Sorry my bad english...

**Comment by archonwang** [comment]
@phoebusnetto ,
Ok, I will test it for some time. Thanks for your reply.

if there's any question I will let you know.

**Comment by phoebusnetto** [comment]
@archonwang Thanks and enjoy the plugin!
:smile:
